name: flutter_app
description: A new Flutter project

environment:
  sdk: '^3.5.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  intl: ^0.19.0
  awesome_notifications: ^0.9.2
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^24.2.3

flutter:
  uses-material-design: true 